Multiple search result
infiniteloopcloud/fireplace pull request #1
Opened 2022-03-03 13:41 UTC by borosr

2022-03-04 07:30 UTC, PumpkinSeed requested changes

2022-03-04 07:30 UTC, PumpkinSeed commented on fireplace.go
> +func (h Handler) searchFile(path, searchFor string) []searchScanResult {
Can you use the SearchResult here?

2022-03-04 10:19 UTC, borosr commented on fireplace.go
> +func (h Handler) searchFile(path, searchFor string) []searchScanResult {
Only if I add the fileID to the function parameters.

2022-03-04 10:22 UTC, borosr commented on fireplace.go
> +func (h Handler) searchFile(path, searchFor string) []searchScanResult {
Done

2022-03-05 15:52 UTC, PumpkinSeed commented on fireplace.go
> +func (h Handler) searchFile(path, searchFor string) []searchScanResult {
Actually not, I think you need to remove the searchScanResult at all. You just set the FileID field later.

2022-03-07 13:22 UTC, PumpkinSeed approved these changes

2022-03-07 13:22 UTC, merged